### ISSUE TITLE
Problem with zero-shot image classification

### ISSUE THREAD

**Issue by happychow001** [NVlabs/RADIO#16]
Thanks for your nice work.

Recently I encountered some problems while reproducing the zero-shot image classification in imagine-1k. The radio model does not seem to include the code of the student head, so that I can't align the image features of radio to the text features of open-clip during testing. Could you release the student head code?

**Comment by mranzinger** [comment]
I will try to get this put together. I agree, the heads are useful!

As a prerequisite, you'll need a fairly recent version of [OpenCLIP](https://github.com/mlfoundations/open_clip/tree/main) installed. You'll know you have a new enough version if this model architecture is present in your install: https://github.com/mlfoundations/open_clip/blob/main/docs/openclip_results.csv#L2

**Comment by happychow001** [comment]
Thanks for your commit.

I still can't reproduce it. It seems because some configs are missing when instanting open_clip_adaptor.

**Comment by mranzinger** [comment]
I'm happy to report that Zero Shot classification is now possible using the repo. Refer to `examples/zero_shot_imagenet.py` for the implementation, and `examples/README.md` for usage.

You'll probably need to run `python examples/zero_shot_imagenet.py --force-reload` first, as PyTorch will have the old code cached, and you need to update.
