### ISSUE TITLE
Radio-2.0 

### ISSUE THREAD

**Issue by orrzohar** [NVlabs/RADIO#54]
Hi,
I was wondering if you are going to release higher-resolution RADIO models?
Best,
Orr

**Comment by gheinrich** [comment]
Hello and thanks for your question! Yes, we have released the weights of our 2nd iteration of RADIO. You may refer to this [section](https://github.com/NVlabs/RADIO?tab=readme-ov-file#quick-start-and-model-versions) of the README.

RADIO 2.1 supports input resolutions up to 2048x2048, including non-square images, where both height and width are multiples of 16 (or `16 x vitdet_window_size` if you are using vitdet).

E-RADIO supports any input resolution, including non-square images, where both height and width are multiples of 32.

You may also use the [preferred_resolution](https://github.com/NVlabs/RADIO/blob/main/radio/hf_model.py#L144C9-L144C29) property to help with the rounding of the input resolution to the nearest supported one.

**Comment by mranzinger** [comment]
Yes, to elaborate a bit further, one of the major design goals of RADIO was to avoid being locked into a single resolution. In the past, this is achieved in ViTs by bilinearly interpolating the position embeddings, but the quality of models tends to degrade sharply when doing so. While we still interpolate these embeddings, we changed the training procedure to force the model to learn how to deal with this operation. In the latest version of our [ArXiv paper](https://arxiv.org/abs/2312.06709), you can see the result of this in Figure 3.

RADIOv2 also supports resolutions up to 2048x2048 (so same as v2.1).

I think Greg meant to say the [get_nearest_supported_resolution](https://github.com/NVlabs/RADIO/blob/d6172559157866ab263d2bea6fe2a2450c52b051/radio/hf_model.py#L158) function may be used to do the rounding.

**Comment by orrzohar** [comment]
Thank you!
