### ISSUE TITLE
is there an adaptor for SAM?

### ISSUE THREAD

**Issue by haoxiangzhaotju** [NVlabs/RADIO#65]
Congratulations on having your paper accepted! That's a fantastic achievement! 
I am currently trying to use the RADIO encoder in place of the SAM encoder, but due to the differences in feature dimensions, I cannot directly substitute one for the other. 

I noticed that an adaptor can solve this issue, but it seems there isn't an adaptor specifically for SAM. 

Could you advise me on how to proceed? Should I train a projection layer for this purpose? Is there something I might have overlooked?

Thank you！

**Comment by mranzinger** [comment]
Hello,

RADIOv2 (and RADIOv2.1) both have a SAM adaptor. I attached a modification of [segment-anything](https://github.com/facebookresearch/segment-anything)'s `amg.py` script as an example for you. You can either use the diff file to patch, or copy the example. Hope this helps.

[radio_amg.zip](https://github.com/user-attachments/files/15838160/radio_amg.zip)

**Comment by haoxiangzhaotju** [comment]
Thank you so much！！！！！！！！！

**Comment by sunmengmm** [comment]
@mranzinger 
Thank you very much for providing the trained model and sam inference code, I tested two models: radio_v2.5-b and e-radio_v2, I found in the readme where you mentioned that the throughput of these two models are 556, 3697 (for e-radio_v1). I used the amg code you provided and the single inference time is around 1.53 sec, 1.31 sec for images on size 512x512. I would like to know how this processing time can be minimized?

**Comment by mranzinger** [comment]
Hi. I think your question may be better asked somewhere with SAM experts, as I suspect the bulk of your time is being spent on the decode side, and not the image encoding, which is where RADIO is running. 512px is probably considered small even; SAM itself wants images to be 1024px, and may even be padding to the dimension.

**Comment by sunmengmm** [comment]
> Hi. I think your question may be better asked somewhere with SAM experts, as I suspect the bulk of your time is being spent on the decode side, and not the image encoding, which is where RADIO is running. 512px is probably considered small even; SAM itself wants images to be 1024px, and may even be padding to the dimension.

Thank you very much for your reply and guidance!!!
