### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.RADIO.enable_cpe_support'

### ISSUE THREAD

**Issue by tsw123678** [NVlabs/RADIO#66]
my env info is: 
transformers-4.41.2
timm-1.0.3

**Comment by tsw123678** [comment]
can you offer install tutorials or env requirements？

**Comment by gheinrich** [comment]
Hello, I am unable to reproduce this issue on my end. In my container I am using:
```
timm==0.9.16
transformers==4.40.1
```
I am not sure if the issue stems from the different versions of these libraries. I pushed an update to the HuggingFace model which I hope could help. Do you mind trying again? I'm sorry for asking you to test, I wish I could reproduce the problem.

**Comment by tsw123678** [comment]
> Hello, I am unable to reproduce this issue on my end. In my container I am using:
> 
> ```
> timm==0.9.16
> transformers==4.40.1
> ```
> 
> I am not sure if the issue stems from the different versions of these libraries. I pushed an update to the HuggingFace model which I hope could help. Do you mind trying again? I'm sorry for asking you to test, I wish I could reproduce the problem.

Thanks for your update! This error has not occurred again.
