### ISSUE TITLE
Interpretation of Feature Layers 

### ISSUE THREAD

**Issue by mfischer-ucl** [NVlabs/RADIO#67]
Hi, congrats on the great work on Radio and the CPVR '24 paper, and thanks for open-sourcing the code! 

For DiNO, people have looked into this and have found that the earlier layers encode positional information and the deeper layers encode semantic information (eg [this](https://arxiv.org/abs/2112.05814) excellent work). 

I was wondering whether you have looked into the (semantic) interpretation of the intermediate features learned by Radio, and potentially noticed similar findings? 

Thanks again!

**Comment by mranzinger** [comment]
Hi. Thanks for the paper link. We haven't explicitly followed the analysis in that paper, so thanks for the link. We do know that _some_ difference in information content exists in the earlier layers though, because UPerNet on top of a frozen RADIO improves semantic segmentation, and we even have some results that suggest concatenating the features from different depths yields better VLLM metrics.

**Comment by mfischer-ucl** [comment]
Thanks, this is very helpful. I can confirm that indeed concatenating the features from different network depths seems to achieve better results (I used blocks 8, 16, 23 and 31). 

A quick question on feature dimension: I noticed that the intermediate layer's shape in DiNO is [4097, fdim], where fdim is the DiNO feature dimension (786) and 4097 is 64x64 + the cls token. 

In RADIO, I get (for a 1024p input image) intermediate features of shape [4112, fdim], which is 4096 + 16, so I was assuming that the 16 first dimensions are the cls tokens, too. Can you confirm this is, and if so, that they are appended at the beginning, i.e., [16:, :] are the features?

**Comment by mfischer-ucl** [comment]
Thanks for the quick answer, that's reassuring and good to know. 

We're using the features as input for a downstream attention block that learns dense segmentation. I can't disclose more at the moment, but will update here once there is some work published :) Thanks again ! 👍

**Comment by jrryzh** [comment]
Hi! Thanks for the great work! Just for confirming ,I am using 'radio_v2.5-l' and input rgb size is 224x224, using code below I got feature list of [torch.Size([1, 204, 1024]), torch.Size([1, 204, 1024]), torch.Size([1, 204, 1024])]. In my case, is using each feature by feature[:, 8:, :] correct? And is this way of using different depth features correct (maybe concatenation these features directly)? Thank you for your great help!


`class ModifiedRADIOModel(nn.Module):
    def __init__(self, model_version='radio_v2.5-l', selected_blocks=[8, 16, 23], repo_path='/ssd/home/zhangjinyu/code_repo/RADIO'):
        super(ModifiedRADIOModel, self).__init__()
        self.radio_encoder = torch.hub.load(repo_path, 'radio_model', version=model_version, 
                                            progress=True, skip_validation=True, source='local', trust_repo=False)
        self.radio_encoder.eval()  
        self.selected_blocks = selected_blocks  

    def forward(self, x):
        features = []
        with torch.no_grad():
            x = self.radio_encoder.input_conditioner(x)
            x = self.radio_encoder.model.patch_generator(x) 
            for i, block in enumerate(self.radio_encoder.model.blocks):
                x = block(x)
                if i in self.selected_blocks:
                    features.append(x)
        return features`

**Comment by jrryzh** [comment]
Thank you for your fast reply! I will check into the details and see how it works for my task.

**Comment by jrryzh** [comment]
> One more thing, radio_v2.5-l doesn't run as well as we'd like at lower resolutions (like 224). It seems to be fine at >256px though.

Hi sorry that I found your valuable comment so late. I'm cropping objects from full image then resize it to 224. So is your advice I resize it to > 256px or even larger? Thank u! Looking forward to your reply

**Comment by mranzinger** [comment]
In general, we do better the larger you go. 768px is actually somewhat of a sweet spot. We're working through the release process for the C-RADIOv3 model family, which fixes this problem with low res images, but in the meantime, yes, using slightly higher res crops.
