### ISSUE TITLE
SAM COCO decoder

### ISSUE THREAD

**Issue by kav-hareichert** [NVlabs/RADIO#82]
"For SAM COCO results, we replace the vision backbone of the SAM model with the corresponding RADIO model. The decoder is frozen from the original model."

Can you provide a small example or a notebook for this?

**Comment by gheinrich** [comment]
Hello, our [RADIO space](https://huggingface.co/spaces/nvidia/radio) on HuggingFace extracts SAM masks and shows them in the visualization, can you take a look at how it's done in the [code](https://huggingface.co/spaces/nvidia/radio/blob/main/app.py)?

**Comment by kav-hareichert** [comment]
Thank you for your reply. Thats very helpfull.
