### ISSUE TITLE
How to replicate the results of feature visualization

### ISSUE THREAD

**Issue by zhudongwork** [NVlabs/RADIO#85]
I use the `visualize_features.py` , download the model `https://huggingface.co/nvidia/RADIO-L` ,  set the `use_huggingface=True`
![image](https://github.com/user-attachments/assets/17c97c6c-ff7e-4124-abe1-6e3b781eaa6e)

then change the `load_model` to use local model:
![image](https://github.com/user-attachments/assets/d1e6ea9f-42fe-4908-9dd6-bccf2659e597)

set `args.resolution = (1024, 1024)`

then, I get the result:
![vis_3](https://github.com/user-attachments/assets/19cf9b03-f7c2-40b4-ac9d-726037d72295)

the origial img is there:
![vis_3_ori](https://github.com/user-attachments/assets/417ff2be-d4ad-4c15-9825-5827d7a5e3bc)

other case:
![vis_4](https://github.com/user-attachments/assets/f48cf856-b429-41a5-a7a2-5a28b93dc0e4)

The results have a significant gap from the effects in the paper, did I do something wrong?

**Comment by mranzinger** [comment]
Can you describe which gap you're referring to? Certainly the coloring is different for the image with quokkas because you're handing it an image that includes the header and text, which isn't how the paper figures were generated (we used only the original image).

**Comment by zhudongwork** [comment]
Forgive my carelessness, I have recropped the image and removed the unnecessary text, but the effect is not much different from before. The difference I described refers to the fact that the feature visualization diagram of RADIO-L shown in the paper is clearly outlined, but my running results look blurred at the edges. What could be the possible problem?

my result:
![vis_3](https://github.com/user-attachments/assets/351e0e07-0bd0-400f-95e1-4986b51f2016)

result in paper:
![image](https://github.com/user-attachments/assets/a4e8153e-4b50-4d72-a47d-c21104af7546)

**Comment by mranzinger** [comment]
Ah, I see what's going on. The paper result you're looking at is for the SAM adaptor. SAM produces strong edge features. You'd be able to reproduce that result with `python visualize_features.py --adaptor-name sam ...`, however, you wouldn't be able to use huggingface for it since adaptors are currently only supported via TorchHub.

**Comment by zhudongwork** [comment]
Thank you for your answer! When using Radio to replace the visual encoder in LAVA, was an adaptor also used?

**Comment by gheinrich** [comment]
Hello, for the LLaVA integration, we used the frozen features of the RADIO backbone (we did not use an adaptor).

**Comment by zhudongwork** [comment]
> 您好，对于 LLaVA 集成，我们使用了 RADIO 主干网的冻结功能（我们没有使用适配器）。

In the LLava training framework, does the RADIO encoder feature use the features from the last layer or from the penultimate layers?

**Comment by gheinrich** [comment]
Hello, we use the last layer. You can also check the integration in VILA, which is based on a LLaVA implementation, there: https://github.com/NVlabs/VILA/blob/main/llava/model/multimodal_encoder/radio_encoder.py

**Comment by zhudongwork** [comment]
Thank you very much for your help, I will give it a try.
