### ISSUE TITLE
loading radio_v2.5-h from huggingface

### ISSUE THREAD

**Issue by gaowei724** [NVlabs/RADIO#95]
Thanks for your great work. I notice that you have released [radio_v2.5-h.pth.tar](https://huggingface.co/nvidia/RADIO/blob/main/radio_v2.5-h.pth.tar) in [nvidia/RADIO](https://huggingface.co/nvidia/RADIO/tree/main).
But when i try to load model from nvidia/RADIO, I found the model is radio_v2.1([config.json](https://huggingface.co/nvidia/RADIO/blob/main/config.json)) . It's more convient to load and save model use AutoModel.from_pretrained() in some case, so have you released the radio_v2.5-h's huggingface version repo? Thx.

**Comment by gheinrich** [comment]
Hello, I pushed the model to `nvidia/RADIO-H`.

**Comment by gaowei724** [comment]
> Hello, I pushed the model to `nvidia/RADIO-H`.

Thanks, it works now.
