### ISSUE TITLE
use radio as backbone in deformable detr for object detection？

### ISSUE THREAD

**Issue by haoxiangzhaotju** [NVlabs/RADIO#96]
Could radio be used to replace the backbone of deformable DETR? From my understanding, since radio incorporates DinoV2, it should be directly applicable to object detection. However, after replacing the backbone of deformable DETR with radio, the object detection performance was very poor. Have you conducted similar experiments, or is there an issue with my approach?

**Comment by haoxiangzhaotju** [comment]
In my testing, the accuracy is almost zero, and all the bounding boxes are located in the lower right corner. For the input images, I manually subtracted the mean and divided by the variance. However, I found that this operation does not place the input within the [0,1] range. After some debugging, I discovered that the maximum value reaches 2.64. Could this have an impact on the results? I sincerely appreciate your patience and assistance.

**Comment by mranzinger** [comment]
Yeah, you're basically double-normalizing the inputs, as RADIO does that internally too, unless you disable it.

After instantiating radio, just call `radio_model.make_preprocessor_external()` before using it, and then you can pre-normalize the inputs as before. Give that a try, and let me know what you find.

**Comment by haoxiangzhao12138** [comment]
After following your suggested modifications, the detection results have returned to normal, and I am very grateful for your help! However, when I was reviewing the code in mmseg, I noticed that in the forward process of radio, the input is divided by 255 to ensure the values remain within the [0,1] range. If I have already applied normalization, do I still need to perform this step? Thank you again for your assistance.

**Comment by haoxiangzhaotju** [comment]
After following your suggested modifications, the detection results have returned to normal, and I am very grateful for your help! However, when I was reviewing the code in mmseg, I noticed that in the forward process of radio, the input is divided by 255 to ensure the values remain within the [0,1] range. If I have already applied normalization, do I still need to perform this step? Thank you again for your assistance.

**Comment by mranzinger** [comment]
If you've already applied normalization, and if you've already called `make_preprocessor_external()`, then you don't need to do anything else, as radio now expects the inputs to be mean centered and unit std.

**Comment by haoxiangzhaotju** [comment]
thank you！！

**Comment by haoxiangzhaotju** [comment]
![image](https://github.com/user-attachments/assets/f17d24e7-d171-48d9-9986-08ef74a6c514)
I apologize for bothering you again. Based on my experiments, I tested three scenarios: directly inputting the image into the model without manual normalization or applying make_preprocessor_external() (represented by the pink line in the graph); dividing the input image by 255, following the method used in line 58 of mmseg/radio.py (represented by the yellow line in the graph); and applying make_preprocessor_external() along with dividing the input image by 255 (represented by the purple line). These results have left me confused. According to your explanation, if make_preprocessor_external() is not applied, the model should be able to directly accept images with pixel values in the [0, 255] range. However, in my experiments, dividing the RGB values by 255 and sending images with pixel values in the [0, 1] range into the model yielded better results. Could you help me understand where I might be going wrong?

Additionally, I would like to ask about the differences between loading models using torch.hub.load and AutoModel.from_pretrained. If I use the latter, would the way the images are preprocessed or initialized change?

**Comment by gheinrich** [comment]
Hello, if `make_preprocessor_external()` is not called then the model expects inputs in the `[0, 1]` range thus would you need to divide int8 pixels values by 255. `torch.hub.load` and `AutoModel.from_pretrained` will be similar in that respect.

So your choices are:

* Call `make_preprocessor_external()` and in that case, inputs are expected to be normalized with zero mean and unit variance,
* Not call `make_preprocessor_external()` and in that case, inputs are expected to be in `[0,1]` range (thus you need a division by 255 if you loaded the image using PIL).

**Comment by jrryzh** [comment]
Hi, thanks for the great work! I have a question about preprocessing rgb images, so if I have an rgb image, all i have to do is divide it by 255. And if I use the code below to preprocess it (using the Imagenet mean and std), It would be bad to the results, is my understanding correct?  Thanks!

```
    def rgb_transform(rgb):
        rgb_ = np.transpose(rgb, (2, 0, 1)) / 255
        _mean = (0.485, 0.456, 0.406)
        _std = (0.229, 0.224, 0.225)
        for i in range(3):
            rgb_[i, :, :] = (rgb_[i, :, :] - _mean[i]) / _std[i]
        return rgb_
```

**Comment by jrryzh** [comment]
Thank u for your fast reply! It seems that I had my rgb get normalized twice and stats between CpenCLIP and ImageNet is slightly different. Now I have revised my code and hope to see some improvements. Thanks!
